In [1]:
## 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

# NumPy stands for “Numerical Python” and it is the standard Python library used for working with arrays , linear algebra, and other numerical computations. NumPy is written in C, making NumPy arrays faster and more memory efficient than Python lists or arrays.
#Performance: NumPy’s array operations are executed at compiled C speed, making them significantly faster than equivalent operations performed using Python lists.
#Memory Efficiency: NumPy arrays use contiguous memory blocks, reducing overhead compared to Python lists


In [2]:
## 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

#The np. mean() method returns the arithmetic mean, but the np. average() function returns the algebraic mean if no additional parameters are specified, but it may also be used to compute a weighted average.

In [3]:
## 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

#By using the slicing method 
#[::-1]
#putting this keyword behind the array make it reverse.


In [5]:
##  4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

#we can determine the data type of element in a numpy array by using .dtype in the suffix of the array
#example = arr.dtype
# we can also create the array which has only one datatype
#example= 
# arr = np.array([1, 2, 3, 4], dtype='S')
#this will make all the array in string 
#data types in memory management and performance plays a crucial role because the data type tells the compiler of the amount of data stored and its data type does maiking it efficient for the compiler to search 


In [6]:
## 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

#ndarrays are n-dimmension array used to store data, it is homogeneous
# we can also use varies operation on the elements in the array
#They differ from list in many aspects like-
#memory efficiency-list are not memory efficient but the numpy array are more memory efficient
#mathematical operation-we cannot apply much mathematical operation on list but thereby using numpy array allows the user to use various mathematical operation 


In [8]:
## 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

#The important feature why user use numpy array over lists is performance
#performance is the important factor in coding
#numpy array is faster than list because of its homogeneous type and also numpy compiles the code in c language and as we know that c langauage is fast language.thus the numpy array code executes faster and it takes less time than the list

In [13]:
##  7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

#numpy.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.
#numpy.vstack() function is used to stack the sequence of input arrays vertically to make a single array.

import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print('the use of vstack=',np.vstack((arr1,arr2)))
print('the use of vstack=',np.hstack((arr1,arr2)))


the use of vstack= [[1 2 3]
 [4 5 6]]
the use of vstack= [1 2 3 4 5 6]


In [14]:
## 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

#flipud()=Reverse the order of elements along axis 0 (up/down).For a 2-D array, this flips the entries in each column in the up/down direction. Rows are preserved, but appear in a different order than before.
#fipr()=Reverse the order of elements along axis 1 (left/right).For a 2-D array, this flips the entries in each row in the left/right direction. Columns are preserved, but appear in a different order than before.

In [15]:
## 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

#With the help of array_split() method, we can get the splitted array of having different dimensions by using numpy.array_split() method.
#it splits the data on the basis of indexes

In [17]:
##  10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations

#Broadcasting is the concept of making arrays with different shapes compatible for arithmetic operations.The numpy. broadcast() function is used to apply binary operations to arrays of different shapes.
#Vectorized operations in NumPy enable the use of efficient, pre-compiled functions and mathematical operations on NumPy arrays and data sequences. Vectorization is a method of performing array operations without the use of for loops.

In [18]:
                                            #PRACTICAL QUESTION#

In [25]:
## 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np
np.random.randint(1,100, size = (3, 3))

array([[54, 10, 10],
       [ 1, 11, 54],
       [47, 56,  4]])

In [26]:
##  2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

array1=np.array([1,2,3,4,5,6,7,8,9,10])
array2=array1.reshape(2,5)
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
array2.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [32]:
## 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

array1=np.random.rand(4,4)
np.pad(array1, pad_width=1, mode='constant', constant_values=0)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.21298335, 0.12113358, 0.17131207, 0.61074587,
        0.        ],
       [0.        , 0.69142668, 0.42450873, 0.10076604, 0.26799619,
        0.        ],
       [0.        , 0.09283794, 0.21594185, 0.58358695, 0.12297603,
        0.        ],
       [0.        , 0.65256783, 0.70420967, 0.37244332, 0.92554439,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [35]:
## 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

array1=np.random.randint(10,60, size = (3, 3))


In [40]:
##5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
array1=np.array(['python', 'numpy', 'pandas'])
print(np.char.upper(array1))
print(np.char.lower(array1))

['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']


In [2]:
##  6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np
array1=np.array(['python', 'numpy', 'pandas'])
space=np.char.join(' ',array1)

In [3]:
space

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

In [15]:
##  7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

array1=np.array([[2,4,6],[3,4,8]])
array2=np.array([[5,3,6],[9,2,6]])
print('addition =\n',array1+array2)
print('subtraction =\n',array1-array2)
print('multiplication =\m',array1*array2)
print('division =\n',array1/array2)

addition =
 [[ 7  7 12]
 [12  6 14]]
subtraction =
 [[-3  1  0]
 [-6  2  2]]
multiplication =\m [[10 12 36]
 [27  8 48]]
division =
 [[0.4        1.33333333 1.        ]
 [0.33333333 2.         1.33333333]]


In [16]:
##  8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [85]:
##  9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

def isprime(x):
    for i in range(1,101):
        if(x%i==0):
            continue
        else:
            print(x)

array1=np.random.randint(0,100,size=(100))
lsit=[]
for i in array1:
    lsit.append(i)
array1

array([ 9,  8, 14, 56, 15, 60, 92, 56, 80, 93, 81,  7, 52, 58, 50, 14, 44,
       93, 19, 15,  1, 80, 26, 42, 21, 24, 91, 81, 18, 38, 20, 70, 86,  3,
        7, 26, 60,  9, 61, 40, 76, 24, 16, 88,  9, 25, 83, 98, 27, 81, 30,
       40, 15, 71, 39, 27, 81, 60, 45, 81, 93, 22, 29, 66, 33, 49, 17, 61,
       38, 85, 49, 80, 58, 63, 34, 36, 77, 89, 42, 84, 71, 69, 57, 90, 41,
       35, 36,  0, 83, 77, 96, 79, 99, 21, 84, 29, 55, 28, 60, 60])

In [ ]:
##  10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

In [122]:
temperatures = np.random.randint(20,51,size=(28))
 
n = len(temperatures)
 
sum = 0
for temp in temperatures[0:8]:
    sum += temp
    average=sum/n
print(average)
     
for temp in temperatures[8:15]:
    sum += temp
    average=sum/n
print(average)
    
for temp in temperatures[15:22]:
    sum += temp
    average=sum/n
print(average)
    
for temp in temperatures[22:29]:
    sum += temp
    average=sum/n
print(average)
    


10.107142857142858
18.0
24.964285714285715
31.642857142857142
